version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app:consistent
      - /app/node_modules
    command: npm run dev
